version: '3.8'

services:
  # Login Microservice
  login_service:
    build:
      context: .
      dockerfile: ./login_backend_api_python/Dockerfile
    container_name: mastercook_login_service
    restart: always
    environment:
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_Ndhucmx5Rv2r1Ni7ocS
      - DB_HOST=mysql-3bbd1558-xboxgar56-040e.g.aivencloud.com
      - DB_PORT=16152
      - DB_NAME=defaultdb
      - JWT_SECRET_KEY=mastercook-super-secret
    ports:
      - "5001:5001"
    networks:
      - mastercook_network

  # Workshop Microservice
  workshop_service:
    build:
      context: .
      dockerfile: ./workshop_backend_api_python/Dockerfile
    container_name: mastercook_workshop_service
    restart: always
    environment:
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_Ndhucmx5Rv2r1Ni7ocS
      - DB_HOST=mysql-3bbd1558-xboxgar56-040e.g.aivencloud.com
      - DB_PORT=16152
      - DB_NAME=defaultdb
      - JWT_SECRET_KEY=mastercook-super-secret
    ports:
      - "5002:5002"
    networks:
      - mastercook_network

  # Reservation Microservice
  reservation_service:
    build:
      context: .
      dockerfile: ./reservation_backend_api_python/Dockerfile
    container_name: mastercook_reservation_service
    restart: always
    environment:
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_Ndhucmx5Rv2r1Ni7ocS
      - DB_HOST=mysql-3bbd1558-xboxgar56-040e.g.aivencloud.com
      - DB_PORT=16152
      - DB_NAME=defaultdb
      - JWT_SECRET_KEY=mastercook-super-secret
    ports:
      - "5003:5003"
    depends_on:
      - workshop_service
    networks:
      - mastercook_network

  # Payment Microservice
  payment_service:
    build:
      context: .
      dockerfile: ./payment_backend_api_python/Dockerfile
    container_name: mastercook_payment_service
    restart: always
    environment:
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_Ndhucmx5Rv2r1Ni7ocS
      - DB_HOST=mysql-3bbd1558-xboxgar56-040e.g.aivencloud.com
      - DB_PORT=16152
      - DB_NAME=defaultdb
      - JWT_SECRET_KEY=mastercook-super-secret
      - STRIPE_SECRET_KEY=sk_test_BQokikJOvBiI2HlWgH4olfQ2
      - RESERVATION_SERVICE_URL=http://reservation_service:5003
    ports:
      - "5004:5004"
    depends_on:
      - reservation_service
    networks:
      - mastercook_network

  # Booking Microservice (Facade/Gateway)
  booking_service:
    build:
      context: .
      dockerfile: ./booking_backend_api_python/Dockerfile
    container_name: mastercook_booking_service
    restart: always
    environment:
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_Ndhucmx5Rv2r1Ni7ocS
      - DB_HOST=mysql-3bbd1558-xboxgar56-040e.g.aivencloud.com
      - DB_PORT=16152
      - DB_NAME=defaultdb
      - JWT_SECRET_KEY=mastercook-super-secret
      - LOGIN_SERVICE_URL=http://login_service:5001
      - WORKSHOP_SERVICE_URL=http://workshop_service:5002
      - RESERVATION_SERVICE_URL=http://reservation_service:5003
      - PAYMENT_SERVICE_URL=http://payment_service:5004
    ports:
      - "5008:5008"
    depends_on:
      - login_service
      - workshop_service
      - reservation_service
      - payment_service
    networks:
      - mastercook_network

networks:
  mastercook_network:
    driver: bridge
