name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: mastercookregistry
  RESOURCE_GROUP: MasterCookGroup
  CONTAINER_APP_ENVIRONMENT: mastercook-environment
  REGION: eastus

jobs:
  build-and-push:
    # ... (todo el contenido original de build-and-push se mantiene igual) ...

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    environment: workflows
    
    steps:
      - name: Install Correct Azure CLI Version
        run: |
          # Instalar versión específica de Azure CLI y extensión containerapp
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version
          az extension remove --name containerapp -y
          az extension add --name containerapp --version 1.0.0 -y

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container Apps
        run: |
          services=(
            "login-service:login_service:5001"
            "workshop-service:workshop_service:5002"
            "reservation-service:reservation_service:5003"
            "payment-service:payment_service:5004"
            "booking-service:booking_service:5008"
          )

          for service in "${services[@]}"; do
            IFS=':' read -r app_name image_name target_port <<< "$service"
            
            echo "🚀 Deploying $app_name..."
            az containerapp update \
              --name $app_name \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --environment ${{ env.CONTAINER_APP_ENVIRONMENT }} \
              --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/$image_name:${{ github.sha }} \
              --set-env-vars \
                DB_USER='avnadmin' \
                DB_PASSWORD='AVNS_Ndhucmx5Rv2r1Ni7ocS' \
                DB_HOST='mysql-3bbd1558-xboxgar56-040e.g.aivencloud.com' \
                DB_PORT='16152' \
                DB_NAME='defaultdb' \
                JWT_SECRET_KEY='mastercook-super-secret' \
                RESERVATION_SERVICE_URL='http://reservation-service.internal' \
                STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
                GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              --ingress external \
              --target-port $target_port
          done

      - name: Verify Deployment
        run: |
          echo "=== Public URLs ==="
          az containerapp list \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --query "[].{Name:name, URL:properties.configuration.ingress.fqdn}" \
            -o table
