name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: mastercookregistry
  RESOURCE_GROUP: MasterCookGroup
  CONTAINER_APP_ENVIRONMENT: mastercook-environment
  REGION: eastus

jobs:
  build-and-push:
    # ... (el contenido de build-and-push se mantiene igual) ...

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    environment: workflows
    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Container Apps
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Función para desplegar servicios con configuración pública
          deploy_public_service() {
            local service_name=$1
            local image_name=$2
            local port=$3
            local env_vars=$4
            
            echo "Deploying $service_name..."
            az containerapp update \
              --name $service_name \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/$image_name:${{ github.sha }} \
              --ingress external \
              --target-port $port \
              --env-vars $env_vars
          }

          # Desplegar todos los servicios con configuración pública
          deploy_public_service "login-service" "login_service" 5001 \
            "DB_USER=avnadmin DB_PASSWORD=AVNS_Ndhucmx5Rv2r1Ni7ocS DB_HOST=mysql-3bbd1558-xboxgar56-040e.g.aivencloud.com DB_PORT=16152 DB_NAME=defaultdb JWT_SECRET_KEY=mastercook-super-secret GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"

          deploy_public_service "workshop-service" "workshop_service" 5002 \
            "DB_USER=avnadmin DB_PASSWORD=AVNS_Ndhucmx5Rv2r1Ni7ocS DB_HOST=mysql-3bbd1558-xboxgar56-040e.g.aivencloud.com DB_PORT=16152 DB_NAME=defaultdb JWT_SECRET_KEY=mastercook-super-secret"

          deploy_public_service "reservation-service" "reservation_service" 5003 \
            "DB_USER=avnadmin DB_PASSWORD=AVNS_Ndhucmx5Rv2r1Ni7ocS DB_HOST=mysql-3bbd1558-xboxgar56-040e.g.aivencloud.com DB_PORT=16152 DB_NAME=defaultdb JWT_SECRET_KEY=mastercook-super-secret"

          deploy_public_service "payment-service" "payment_service" 5004 \
            "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} RESERVATION_SERVICE_URL=http://reservation-service.internal"

          # Configuración especial para el API Gateway (booking-service)
          PUBLIC_URLS="LOGIN_SERVICE_URL=https://login-service.${{ env.CONTAINER_APP_ENVIRONMENT }}.${{ env.REGION }}.azurecontainerapps.io"
          PUBLIC_URLS+=" WORKSHOP_SERVICE_URL=https://workshop-service.${{ env.CONTAINER_APP_ENVIRONMENT }}.${{ env.REGION }}.azurecontainerapps.io"
          PUBLIC_URLS+=" RESERVATION_SERVICE_URL=https://reservation-service.${{ env.CONTAINER_APP_ENVIRONMENT }}.${{ env.REGION }}.azurecontainerapps.io"
          PUBLIC_URLS+=" PAYMENT_SERVICE_URL=https://payment-service.${{ env.CONTAINER_APP_ENVIRONMENT }}.${{ env.REGION }}.azurecontainerapps.io"

          az containerapp update \
            --name booking-service \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/booking_service:${{ github.sha }} \
            --ingress external \
            --target-port 5008 \
            --env-vars $PUBLIC_URLS

    - name: Verify Deployment
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Función para obtener URLs públicas
          get_public_url() {
            local service_name=$1
            az containerapp show --name $service_name --resource-group ${{ env.RESOURCE_GROUP }} \
              --query "properties.configuration.ingress.fqdn" -o tsv
          }

          echo "=== Public URLs ==="
          for service in login-service workshop-service reservation-service payment-service booking-service; do
            echo "$service: https://$(get_public_url $service)"
          done
